### ISSUE TITLE
Plugin de stickers e separação entre salas

### ISSUE THREAD

**Issue by prppedro** [lucasberti/telegrao#4]
Os stickers criados como o novo plugin em C++ não fazem distinção de chat. Além do mais, o acionamento do comando não leva em conta a sala, também, podendo um usuário presente nos dois chats iniciar o plugin numa sala e terminar noutra.

**Comment by lucasberti** [comment]
O compartilhamento de plugins é uma feature, pra aumentar a diversidade de plugins em ambos os chats. Sobre o segundo problema, será corrigido em breve.
